ClienteRegalosDulces/Controllers/RecordatorioController.cs
using ClienteRegalosDulces.Services;
using Microsoft.AspNetCore.Mvc;
using Polly.CircuitBreaker;
using System.ComponentModel;
using DataModel.Tables;
using DataModel.Models;
using ClienteRegalosDulces.Helpers;

namespace ClienteRegalosDulces.Controllers
{
    [DisplayName("Manejo de Usuarios")]
    public class RecordatorioController : Controller
    {
        private readonly IRecordatorioService _svc;
        private readonly IWsGroupService _svcWsGrp;
        private readonly IMensajeService _svcMsg;

        public RecordatorioController(IRecordatorioService RecordatorioService, IWsGroupService svcWsGrp, IMensajeService msgSvc)
        {
            _svc = RecordatorioService ?? throw new ArgumentNullException(nameof(RecordatorioService));
            _svcWsGrp = svcWsGrp;
            _svcMsg = msgSvc;
        }

        [DisplayName("Pantalla de Inicio")]
        public IActionResult Index()
        {
            return View();
        }

        [DisplayName("Pantalla de Inicio")]
        public async Task<IActionResult> Crud(int id)
        {
            ViewBag.groups = await _svcWsGrp.GetAllAsync(new Filter());
            return View(id > 0 ? await _svc.GetItem(id) : new Recordatorio());
        }

        [HttpPost]
        [DisplayName("Acceder a Datos")]
        public async Task<IActionResult> SendTestMessage([FromBody] Filter data)
        {
            try
            {
                var r = await _svc.SendMsgTest(data);
                return Ok(new { rs = r.Success ? "ok" : "fail", msg = r.Message });
            }
            catch (Exception ex)
            {
                ex.LogEx();
                HandleBrokenCircuitException();
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
        }

        [HttpPost]
        [DisplayName("Acceder a Datos")]
        public async Task<IActionResult> GetData([FromBody] Filter data)
        {
            try
            {
                var r = await _svc.GetAllAsync(data);
                return Ok(new { rs = r.Any() ? "ok" : "fail", data = r });
            }
            catch (Exception ex)
            {
                ex.LogEx();
                HandleBrokenCircuitException();
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
        }

        [HttpPost]
        [DisplayName("Borrado de Datos")]
        public async Task<IActionResult> Delete([FromBody] Filter data)
        {
            try
            {
                var idAcc = int.Parse(data.parameters["id"].ToString());
                var r = await _svc.GetItem(idAcc);
                if (r.IdRecord == 0)
                    return Ok(new { rs = "falla", msg = "" });

                var y = await _svc.Delete(r);
                return Ok(new { rs = y ? "ok" : "falla", msg = "" });
            }
            catch (Exception ex)
            {
                ex.LogEx();
                HandleBrokenCircuitException();
                return Ok(new { msg = "Hubo un error al intentar borrar..." });
            }
        }

        [HttpPost]
        [DisplayName("Guardado/Edicion")]
        public async Task<IActionResult> Save([FromForm] Recordatorio model)
        {
            try
            {
                var r = new Recordatorio();
                var r2 = new Mensaje();

                if (!Request.Form.TryGetValue("msg", out var msgData))
                    return View(nameof(Crud));

                if (!Request.Form.TryGetValue("grps", out var groups))
                    return View(nameof(Crud));

                if (string.IsNullOrEmpty(msgData) || string.IsNullOrEmpty(groups))
                    return View(nameof(Crud));

                if (model.IdRecord == 0)
                {
                    r2 = await _svcMsg.Add(new Mensaje()
                    {
                        DesMsg = msgData.ToString(),
                    });

                    if (r2.IdMsg == 0)
                        return View(nameof(Crud));

                    model.IdMsg = r2.IdMsg;
                    model.IdGrps = groups.ToString();
                    r = await _svc.Add(model);
                }
                else
                {
                    if (!model.IdMsg.HasValue)
                        return View(nameof(Crud));

                    var msgRow = await _svcMsg.GetItem(model.IdMsg.Value);
                    if (msgRow.IdMsg == 0)
                        return View(nameof(Crud));

                    msgRow.DesMsg = msgData.ToString();
                    r2 = await _svcMsg.Update(msgRow);
                    if (r2.IdMsg == 0)
                        return View(nameof(Crud));

                    model.IdGrps = groups.ToString();
                    r = await _svc.Update(model);
                }

                if (r.IdRecord > 0)
                    return RedirectToAction("Index");
            }
            catch (BrokenCircuitException ex)
            {
                HandleBrokenCircuitException();
                ex.LogEx();
            }
            catch (Exception ex)
            {
                ex.LogEx();
            }

            return Ok(nameof(Crud));
        }

        private void HandleBrokenCircuitException()
        {
            ViewBag.InoperativeMsg = "Service is inoperative, please try later on. (Business Msg Due to Circuit-Breaker)";
        }
    }
}

ClienteRegalosDulces/Views/Recordatorio/Crud.cshtml
@model DataModel.Tables.Recordatorio
@{
    ViewData["Title"] = "Recordatorio Registro/Edicion";

    var idGrpsStr = Model.IdGrps == "-" ? [] : Model.IdGrps.Split(',');
    var idGrps = Array.Empty<int>();

    if (idGrpsStr.Length != 0)
        idGrps = idGrpsStr.Select(int.Parse).ToArray();
}

<nav class="app-breadcrumb" aria-label="breadcrumb">
    <ol class="breadcrumb ms-0">
        <li class="breadcrumb-item">Recordatorio</li>
        <li class="breadcrumb-item" aria-current="page">Datos General</li>
    </ol>
</nav>
<h1 class="subheader-title position-relative">
    Datos Generales
    <small> detalle de datos de Recordatorio</small>
</h1>
<div class="main-content">
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form asp-action="Save" asp-controller="Recordatorio" method="post">
                        <input type="hidden" asp-for="IdRecord" value="@Model.IdRecord">
                        <input type="hidden" asp-for="IdMsg" value="@Model.IdMsg">
                        <input type="hidden" asp-for="IdGrps" value="@Model.IdGrps">
                        <input type="hidden" asp-for="Token" value="@Model.Token">
                        <input type="hidden" asp-for="RegDat" value="@Model.RegDat">
                        <div class="row mb-3">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="form-label">Grupos a donde se va publicitar</label>
                                    <select class="form-control" name="grps" multiple id="grps">
                                        @foreach (DataModel.Tables.WsGroup item in ViewBag.groups)
                                        {
                                            if (idGrps.Length != 0)
                                            {
                                                if(idGrps.Contains(item.IdGrp))
                                                {
                                                    <option value="@item.IdGrp" selected>@item.GrpNam</option>
                                                }
                                                else
                                                {
                                                    <option value="@item.IdGrp">@item.GrpNam</option>
                                                }
                                            }
                                            else
                                            {
                                                <option value="@item.IdGrp">@item.GrpNam</option>
                                            }

                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label">Hora de publicacion</label>
                                    <input type="time" id="timetoput" asp-for="HourRecord" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="msg" class="form-label">Mensaje</label>
                                    <textarea class="form-control" id="msg" name="msg" rows="8">@(Model.Mensaje != null ? Model.Mensaje.DesMsg : "")</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="form-label">Estado</label>
                                    <select class="form-control" id="IsAct" asp-for="IsAct">
                                        @if (Model.IsAct.Value)
                                        {
                                            <option selected value="true">Activo</option>
                                            <option value="false">Inactivo</option>
                                        }
                                        else
                                        {
                                            <option value="true">Activo</option>
                                            <option selected value="false">Inactivo</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row" mb-3>
                            <div class="col-lg-8">
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Guardar</button>
                                    @if(Model.IdRecord > 0)
                                    {
                                        <button class="btn btn-success" id="sendmsgtest" type="button">Enviar Mensaje como prueba a grupos</button>
                                    }
                                    <a href="@Url.Action("Index", "Recordatorio")" class="btn btn-secondary">Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link href="~/scripts/thirdparty/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/scripts/thirdparty/flatpick/flatpickr.min.css" rel="stylesheet" />
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/scripts/thirdparty/select2/js/select2.full.min.js"></script>
    <script src="~/scripts/thirdparty/flatpick/flatpickr.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#timetoput").flatpickr({
                              enableTime: true,
                              noCalendar: true,
                              dateFormat: "H:i" 
            });

            $("#sendmsgtest").click(async function(){

                if($("#msg").val() == "" || $("#msg").val() == null){
                    Swal.fire("Error", "El mensaje no puede estar vacio", "error");
                    return;
                }

                if($("#grps").val() == "" || $("#grps").val() == null){
                    Swal.fire("Error", "Tiene que tener al menos un grupo al cual enviar el mensaje", "error");
                    return;
                }

                Swal.fire("Info", "Eniando mensajes a grupos", "info");
                Swal.showLoading();
                let data = {
                    parameters: {
                        op: "GetGroupsById",
                        msg: $("#msg").val(),
                        data: $("#grps").val().join(",")
                    }
                };

                let settings = {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(data)
                };

                let response = await fetch("@Url.Action("SendTestMessage", "Recordatorio")", settings);
                let { rs, msg } = await response.json();

                Swal.hideLoading();
                Swal.clickConfirm();

                if (rs == "ok") {
                    Swal.fire("Exito", msg, "success");
                } else {
                    Swal.fire("Error", msg, "error");
                }
            });

            $('#grps').select2();
        });
    </script>
}

ClienteRegalosDulces/Views/Recordatorio/Index.cshtml
@{
    ViewData["Title"] = "Pantalla Principal";
}

<nav class="app-breadcrumb" aria-label="breadcrumb">
    <ol class="breadcrumb ms-0">
        <li class="breadcrumb-item">Recordatorio</li>
        <li class="breadcrumb-item" aria-current="page">Pantalla de Inicio</li>
    </ol>
</nav>
<h1 class="subheader-title position-relative">
    Listado de Recordatorio
</h1>
<div class="main-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div class="row d-flex justify-content-between">
                        <div class="col-md-auto ms-auto">
                            <a href="@Url.Action("Crud", "Recordatorio", new { id = 0 })" target="_blank" class="btn btn-primary">Nuevo +</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="tablaBase" class="table table-striped" role="grid" aria-describedby="dt-basic-example_info">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Mensaje</th>
                                        <th>Hora de envio</th>
                                        <th style="width:3%">Estado</th>
                                        <th style="width:3%">Accion</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Mensaje</th>
                                        <th>Hora de envio</th>
                                        <th style="width:3%">Estado</th>
                                        <th style="width:3%">Accion</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link href="~/scripts/thirdparty/datatables/datatables.min.css" rel="stylesheet" />
}

@section Scripts {
    <script src="~/scripts/thirdparty/datatables/dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            let par = {
                parameters: {}
            };

           let table = $('#tablaBase').DataTable({
                "responsive": true,
                "dom": "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'fB><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'l>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
                buttons: [
                ],
                "ajax": {
                    "url": '@Url.Action("GetData", "Recordatorio")', "contentType": "application/json", "dataSrc": 'data', "type": 'POST', "data": function () { return JSON.stringify(par) }
                },
                "order": [[0, 'desc']],
                "initComplete": function (settings, json) {
                    $('#rwCou').text('( ' + json.data.length + ' )');
                },
                "columnDefs": [{
                    "targets": -1, "data": null,
                    "defaultContent": ""
                }],
                "columns": [
                    { 'data': 'idRecord' },
                    { 'data': 'mensaje.desMsg' },
                    { 'data': 'hourRecord' },
                    { 'data': 'isAct', "render": function (data, type, row) {
                        return row['isAct'] == true ? 'Activo' : 'Inactivo'}
                    },
                    {
                        'data': "null", "render": function (data, type, row) {
                            return `<div class="btn-group">
                                        <button type="button" class="btn btn-info rounded-circle btn-icon" data-bs-toggle="dropdown" aria-expanded="false">
                                            <svg class="sa-icon sa-bold sa-icon-light">
                                                <use href="../../img/sprite.svg#plus-circle"></use>
                                            </svg>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item btnDet" href="javascript:void(0)">Detalles</a>
                                            <a class="dropdown-item btnDel" href="javascript:void(0)">Borrar</a>
                                        </div>
                                    </div>`;
                        }
                    }]
            });

            $('#tablaBase tbody').on('click', '.btnDel', function () {
                let row = $(this).closest('tr');
                if (row.hasClass('child')) { row = row.prev(); }
                let data = table.row(row).data();

                try {
                    let x = {
                        parameters: {
                            'id': data.idRecord
                        }
                    };

                    Swal.fire({
                        title: 'Esta usted seguro?',
                        text: "No podrás revertir esto!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Procesar',
                        showLoaderOnConfirm: true,
                        preConfirm: (r) => {
                            return fetch('@Url.Action("Delete", "Recordatorio")', {
                                method: "POST",
                                headers: {
                                    'Accept': 'application/json',
                                    'Content-Type': 'application/json'
                                },
                                body: JSON.stringify(x)
                                }).then(response => {
                                    if (!response.ok) {
                                        throw new Error(response.statusText)
                                    }
                                    return response.json()
                                }).catch(error => {
                                    Swal.showValidationMessage(`Request failed: ${error}`)
                                })
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        let r = result.value;
                        if (r.rs == "ok") {
                            Swal.fire('Proceso', 'Datos borrados con exito', 'success');
                            table.ajax.reload(function () {
                                $("#rwCou").text((`${table.rows().count()}`));
                            });
                        } else {
                            Swal.fire('Proceso', r.msg != '-' ? r.msg : 'Disculpe, el procesado no puede ser completado', 'error');
                            table.ajax.reload(function () {
                                $("#rwCou").text((`${table.rows().count()}`));
                            });
                        }
                    });
                } catch (e) {
                    console.log(e);
                };
            });

            $('#tablaBase tbody').on('click', '.btnDet', function () {
                let row = $(this).closest('tr');
                if (row.hasClass('child')) { row = row.prev(); }
                let data = table.row(row).data();

                let url = '@Url.Action("Crud", "Recordatorio")/' + data.idRecord;
                let win = window.open(url, '_blank');
                win.focus();
            });

        });
    </script>
}